import Foundation

enum SupportedImageFormats {
    static let folderExtensions: Set<String> = [
        "3fr",
        "apng",
        "arw",
        "avif",
        "bmp",
        "cr2",
        "cr3",
        "crw",
        "cur",
        "dcr",
        "dib",
        "dng",
        "erf",
        "exr",
        "fff",
        "gif",
        "heic",
        "heics",
        "heif",
        "heifs",
        "hif",
        "icns",
        "ico",
        "j2c",
        "j2k",
        "jpc",
        "jpe",
        "jpeg",
        "jfif",
        "jp2",
        "jpf",
        "jpg",
        "jpx",
        "mos",
        "mpo",
        "mrw",
        "nef",
        "nrw",
        "orf",
        "pbm",
        "pef",
        "pgm",
        "png",
        "pnm",
        "ppm",
        "psd",
        "raf",
        "raw",
        "rw2",
        "rwl",
        "sr",
        "sr2",
        "srf",
        "srw",
        "tga",
        "thm",
        "tif",
        "tiff",
        "webp"
    ]

    static let displayNames: [String: String] = [
        "3fr": "RAW",
        "apng": "APNG",
        "arw": "RAW",
        "avif": "AVIF",
        "bmp": "BMP",
        "cr2": "RAW",
        "cr3": "RAW",
        "crw": "RAW",
        "cur": "CUR",
        "dcr": "RAW",
        "dib": "BMP",
        "dng": "DNG",
        "erf": "RAW",
        "exr": "OpenEXR",
        "fff": "RAW",
        "gif": "GIF",
        "heic": "HEIC",
        "heics": "HEICS",
        "heif": "HEIF",
        "heifs": "HEIF",
        "hif": "HEIF",
        "icns": "ICNS",
        "ico": "ICO",
        "j2c": "JPEG 2000",
        "j2k": "JPEG 2000",
        "jpc": "JPEG 2000",
        "jpe": "JPEG",
        "jpeg": "JPEG",
        "jfif": "JPEG",
        "jp2": "JPEG 2000",
        "jpf": "JPEG 2000",
        "jpg": "JPEG",
        "jpx": "JPEG 2000",
        "mos": "RAW",
        "mpo": "MPO",
        "mrw": "RAW",
        "nef": "RAW",
        "nrw": "RAW",
        "orf": "RAW",
        "pbm": "NetPBM",
        "pef": "RAW",
        "pgm": "NetPBM",
        "png": "PNG",
        "pnm": "NetPBM",
        "ppm": "NetPBM",
        "psd": "PSD",
        "raf": "RAW",
        "raw": "RAW",
        "rw2": "RAW",
        "rwl": "RAW",
        "sr": "RAW",
        "sr2": "RAW",
        "srf": "RAW",
        "srw": "RAW",
        "tga": "TGA",
        "thm": "JPEG",
        "tif": "TIFF",
        "tiff": "TIFF",
        "webp": "WebP"
    ]

    static func displayName(for pathExtension: String) -> String? {
        let normalizedExtension = pathExtension.lowercased()
        guard !normalizedExtension.isEmpty else { return nil }
        return displayNames[normalizedExtension] ?? normalizedExtension.uppercased()
    }
}
